
spring:
  application:
    name: icon-pack-generator
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        period: 0
      static-locations: ${STATIC_LOCATIONS}
  mvc:
    async:
      request-timeout: 300000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "${app.base-url}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: email
  datasource:
    url: jdbc:postgresql://localhost:5432/icon_pack_generator
    username: ${POSTGRES_USER:iconpack}
    password: ${POSTGRES_PASSWORD:iconpack123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  transaction:
    default-timeout: 300

server:
  port: 8080
  tomcat:
    connection-timeout: 300000
  servlet:
    session:
      timeout: 4h
      cookie:
        http-only: true
        secure: true # Set to true in production with HTTPS
        # max-age not set - cookie persists as long as browser is open
        # Session will be refreshed on each request (Spring default behavior)

ai:
  services:
    flux-ai:
      enabled: false
    recraft:
      enabled: false
    photon:
      enabled: false
    gpt:
      enabled: true
    banana:
      enabled: false

fal:
  ai:
    api-key: ${FAL_KEY:api-key}
    model-endpoint: fal-ai/flux-pro/v1.1
    timeout-seconds: 120
    max-retries: 3
    aspect-ratio: "1:1"
    num-images: 1
    enable-safety-checker: true

openai:
  api-key: ${OPENAI_API_KEY:your-openai-api-key-here}

stripe:
  secret-key: ${STRIPE_SECRET_KEY:}
  publishable-key: ${STRIPE_PUBLISHABLE_KEY:}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET:}
  products:
    starter-pack:
      id: ${STRIPE_STARTER_PACK_PRODUCT_ID:prod_T46XgiMnbA3uMF}
      price-id: ${STRIPE_STARTER_PACK_PRICE_ID:price_1S7yKeG7H7nvLRCSbS3XAqO9}
      coins: 8
    creator-pack:
      id: ${STRIPE_CREATOR_PACK_PRODUCT_ID:prod_T46ZOSQZOhjxq6}
      price-id: ${STRIPE_CREATOR_PACK_PRICE_ID:price_1S7yMgG7H7nvLRCSvXEf20Ub}
      coins: 18
    pro-pack:
      id: ${STRIPE_PRO_PACK_PRODUCT_ID:pro_pack_product_id}
      price-id: ${STRIPE_PRO_PACK_PRICE_ID:pro_pack_price_id}
      coins: 40

background-removal:
  enabled: true
  rembg-command: rembg
  timeout-seconds: 30
  model: isnet-general-use
  output-dir: generated-images

logging:
  level:
    com:
      gosu:
        iconpackgenerator: INFO
    ai:
      fal:
        client: INFO
    org:
      springframework:
        web:
          client: INFO
      apache:
        http: DEBUG
    httpclient:
      wire: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

callmebot:
  enabled: ${CALLMEBOT_ENABLED}
  phone: ${PHONE_NUMBER}
  apikey: ${CALLMEBOT_API_KEY}

app:
  file-storage:
    base-path: ${FILE_STORAGE_PATH:static/user-icons}
  illustrations-storage:
    base-path: ${FILE_STORAGE_PATH:static/user-illustrations}
  base-url: ${APP_BASE_URL:http://localhost:8080}
  security:
    remember-me:
      key: ${REMEMBER_ME_SECRET_KEY:defaultRememberMeSecretKey123}
  admin:
    email: ${ADMIN_EMAIL:}

sendgrid:
  api-key: ${SENDGRID_API_KEY:your-sendgrid-api-key-here}
  from-email: ${SENDGRID_FROM_EMAIL:noreply@yourdomain.com}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
  show-actuator: false
  paths-to-exclude: /error
