
spring:
  application:
    name: icon-pack-generator
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        period: 0
      static-locations: ${STATIC_LOCATIONS}
  mvc:
    async:
      request-timeout: 300000
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: email
  datasource:
    url: jdbc:postgresql://localhost:5432/icon_pack_generator
    username: ${POSTGRES_USER:iconpack}
    password: ${POSTGRES_PASSWORD:iconpack123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
  transaction:
    default-timeout: 300

server:
  port: 8080
  tomcat:
    connection-timeout: 300000

ai:
  services:
    flux-ai:
      enabled: false
    recraft:
      enabled: false
    photon:
      enabled: false
    gpt:
      enabled: true
    imagen:
      enabled: false

fal:
  ai:
    api-key: ${FAL_KEY:api-key}
    model-endpoint: fal-ai/flux-pro/v1.1
    timeout-seconds: 120
    max-retries: 3
    aspect-ratio: "1:1"
    num-images: 1
    enable-safety-checker: true

openai:
  api-key: ${OPENAI_API_KEY:your-openai-api-key-here}

background-removal:
  enabled: true
  rembg-command: rembg
  timeout-seconds: 30
  model: isnet-general-use
  output-dir: generated-images

logging:
  level:
    com:
      gosu:
        iconpackgenerator: INFO
    ai:
      fal:
        client: INFO
    org:
      springframework:
        web:
          client: INFO
      apache:
        http: DEBUG
    httpclient:
      wire: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

app:
  file-storage:
    base-path: ${FILE_STORAGE_PATH:static/user-icons}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    disable-swagger-default-url: true
  show-actuator: false
  paths-to-exclude: /error
