spring:
  security:
    oauth2:
      client:
        registration:
          google:
            # Using environment variables GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET
            client-id: test
            client-secret: test0-test-test
            scope:
              - openid
              - profile
              - email
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: email

logging:
  level:
    com.gosu.iconpackgenerator.user: INFO

app:
  security:
    remember-me:
      key: localDevRememberMeSecretKey456
